/*
 * Potter Price Service for Marketing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.agiledojo.cdd.marketing.price_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Price
 */
@JsonPropertyOrder({
  Price.JSON_PROPERTY_IN_CENT,
  Price.JSON_PROPERTY_TAX
})

public class Price {
  public static final String JSON_PROPERTY_IN_CENT = "inCent";
  private BigDecimal inCent;

  public static final String JSON_PROPERTY_TAX = "tax";
  private BigDecimal tax;


  public Price inCent(BigDecimal inCent) {
    
    this.inCent = inCent;
    return this;
  }

   /**
   * Get inCent
   * @return inCent
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_IN_CENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getInCent() {
    return inCent;
  }


  public void setInCent(BigDecimal inCent) {
    this.inCent = inCent;
  }


  public Price tax(BigDecimal tax) {
    
    this.tax = tax;
    return this;
  }

   /**
   * Get tax
   * @return tax
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_TAX)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getTax() {
    return tax;
  }


  public void setTax(BigDecimal tax) {
    this.tax = tax;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Price price = (Price) o;
    return Objects.equals(this.inCent, price.inCent) &&
        Objects.equals(this.tax, price.tax);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inCent, tax);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Price {\n");
    sb.append("    inCent: ").append(toIndentedString(inCent)).append("\n");
    sb.append("    tax: ").append(toIndentedString(tax)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

