/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.agiledojo.cdd.producer;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.web.server.LocalServerPort;

import static io.restassured.RestAssured.given;
import static org.springframework.boot.test.context.SpringBootTest.WebEnvironment.RANDOM_PORT;
import static org.springframework.http.HttpStatus.OK;

@SpringBootTest(webEnvironment = RANDOM_PORT)
class AppTest {
    @LocalServerPort
    int port;

    @Test
    void shouldResponseToApiCall() {
        given()
                .port(port)
                .body("[\"I\"]")
                .contentType("application/json")
        .when()
                .post("/priceFor")
        .then().assertThat()
                .statusCode(OK.value());
    }

}
